<html >

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <!-- <link rel=File-List href="ckp_files/filelist.xml"> -->
    <style id="06 Juni 2020_8991_Styles">
         .nama_column_9 {
            padding-top: 1px;
            padding-right: 1px;
            padding-left: 1px;
            color: ;
            font-size: 10.0pt;
            font-weight: 700;
            font-style: normal;
            text-decoration: none;
            font-family: "Segoe UI", sans-serif;
            text-align: center;
            vertical-align: middle;
            border: .5pt solid ;
            white-space: normal;
        }
        .nomor_column_11 {
            padding-top: 1px;
            padding-right: 1px;
            padding-left: 1px;
            color: ;
            font-size: 10.0pt;
            font-weight: 400;
            font-style: normal;
            text-decoration: none;
            font-family: "Segoe UI", sans-serif;
            text-align: center;
            vertical-align: middle;
            border: .5pt solid ;
            white-space: normal;
        }
        .header_isi_column_12 {
            padding-top: 1px;
            padding-right: 1px;
            padding-left: 2px;
            color: ;
            font-size: 10.0pt;
            font-weight: 700;
            font-style: normal;
            text-decoration: none;
            font-family: "Segoe UI", sans-serif;
            text-align: left;
            vertical-align: center;
            border: .5pt solid ;
            white-space: normal;
        }
        .isi_column_right {
            padding-top: 1px;
            padding-right: 3px;
            padding-left: 1px;
            color: ;
            font-size: 10.0pt;
            font-weight: 400;
            font-style: normal;
            text-decoration: none;
            font-family: "Segoe UI", sans-serif;
            text-align: right;
            vertical-align: center;
            border: .5pt;
            border-style: none solid dashed solid;
            white-space: normal;
        }
        .isi_column_left{
            padding-top: 1px;
            padding-right: 1px;
            padding-left: 3px;
            color: ;
            font-size: 10.0pt;
            font-weight: 400;
            font-style: normal;
            text-decoration: none;
            font-family: "Segoe UI", sans-serif;
            text-align: left;
            vertical-align: center;
            border: .5pt;
            border-style: none solid dashed solid;
            white-space: normal;
        }
        .isi_column_center{
            padding-top: 1px;
            padding-right: 1px;
            padding-left: 1px;
            color: ;
            font-size: 10.0pt;
            font-weight: 400;
            font-style: normal;
            text-decoration: none;
            font-family: "Segoe UI", sans-serif;
            text-align: center;
            vertical-align: center;
            border: .5pt;
            border-style: none solid dashed solid;
            white-space: normal;
        }
        .kosong {
            padding-top: 1px;
            padding-right: 1px;
            padding-left: 1px;
            color: ;
            font-size: 10.0pt;
            font-weight: 400;
            font-style: normal;
            text-decoration: none;
            font-family: "Segoe UI", sans-serif;
            text-align: left;
            vertical-align: middle;
            border: 0pt ;
            white-space: normal;
        }
        
        .ckp_t_nama {
            padding-top: 1px;
            padding-right: 1px;
            padding-left: 1px;
            color: ;
            font-size: 16.0pt;
            font-weight: 700;
            font-style: normal;
            text-decoration: none;
            font-family: "Arrus Blk BT", serif;
            text-align: center;
            vertical-align: middle;
            border: 1.5pt solid ;
            white-space: nowrap;
        }


        .judul {
            padding-top: 1px;
            padding-right: 1px;
            padding-left: 1px;
            color: ;
            font-size: 14.0pt;
            font-weight: 700;
            font-style: normal;
            text-decoration: none;
            font-family: "Segoe UI", sans-serif;
            text-align: center;
            vertical-align: bottom;
            white-space: nowrap;
        }

    </style>
</head>

<body>
    <!--[if !excel]>&nbsp;&nbsp;<![endif]-->
    <!--The following information was generated by Microsoft Excel's Publish as Web
Page wizard.-->
    <!--If the same item is republished from Excel, all information between the DIV
tags will be replaced.-->
    <!----------------------------->
    <!--START OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD -->
    <!----------------------------->

    <div id="06 Juni 2020_10668">

        <table style='border-collapse:collapse;table-layout:fixed;width:100%'>
            <col style='width:3.19%'>
            <col style='width:10.48%'>
            <col style='width:29.80%'>
            <col style='width:10.80'>
            <col style='width:5.14%'>
            <col style='width:6.17%'>
            <col style='width:5.66%'>
            <col style='width:7.18%'>
            <col style='width:7.19%'>
            <col style='width:6.17%'>
            <col style='width:8.22%'>
            <tr style='height:40px'>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="ckp_t_nama">CKP-R</td>
            </tr>
            <tr style='height:40px'>
                <td colspan=11 class=judul>CAPAIAN KINERJA PEGAWAI TAHUN 2020</td>
            </tr>
            <tr style='height:14px'>
                <td class="kosong" style='width:3.19%'></td>
                <td class="kosong" style='width:10.48%'></td>
                <td class="kosong" style='width:29.80%'></td>
                <td class="kosong" style='width:10.80'></td>
                <td class="kosong" style='width:5.14%'></td>
                <td class="kosong" style='width:6.17%'></td>
                <td class="kosong" style='width:5.66%'></td>
                <td class="kosong" style='width:7.18%'></td>
                <td class="kosong" style='width:7.19%'></td>
                <td class="kosong" style='width:6.17%'></td>
                <td class="kosong" style='width:8.22%'></td>
            </tr>
            <tr style='height:19px'>
                <td class="kosong" colspan=2>Satuan Organisasi</td>
                <td class="kosong" colspan=3 style="white-space: nowrap;">:<span style=''> </span>{{env('SATKER')}}</td>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong"></td>
            </tr>
            <tr style='height:19px'>
                <td class="kosong" colspan=2 >Nama</td>
                <td class="kosong" colspan=3 style="white-space: nowrap;">:<span style=''> </span>{{ auth()->user()->nama }}</td>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong"></td>
            </tr>
            <tr height=19 style='height:14.25pt'>
                <td height=19 class="kosong" colspan=2 style='height:14.25pt'>Jabatan<span
                        style=''></span></td>
                <td class="kosong" colspan=3 style="white-space: nowrap;">:<span style=''> </span>{{ auth()->user()->jabatan }} {{env('SATKER')}}</td>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong"></td>
            </tr>
            <tr style='height:19px'>
                <td class="kosong" colspan=2 >Periode</td>
                <td class="kosong" colspan=3 style="white-space: nowrap;">:<span style=''> </span>{{$ckp->rentang}}</td>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong"></td>
            </tr>
            <tr height=15 style='height:11.25pt'>
                <td height=15 class="kosong" style='height:11.25pt'></td>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong"></td>
            </tr>
            <tr style='height:50px'>
                <td rowspan=2 class='nama_column_9'>No</td>
                <td colspan=2 rowspan=2 class='nama_column_9'>Uraian Kegiatan</td>
                <td rowspan=2 class='nama_column_9'>Satuan<span style=''></span></td>
                <td colspan=3 class='nama_column_9'>Kuantitas</td>
                <td rowspan=2 class='nama_column_9'>Tingkat Kualitas<span style=''></span>(%)</td>
                <td rowspan=2 class='nama_column_9'>Kode Butir Kegiatan</td>
                <td rowspan=2 class='nama_column_9'>Angka Kredit</td>
                <td rowspan=2 class='nama_column_9'>Keterangan</td>
            </tr>
            <tr style='height:25px'>
                <td class='nama_column_9'>Target</td>
                <td class='nama_column_9'>Realisasi</td>
                <td class='nama_column_9'>%</td>
            </tr>
            <tr height=21 style='height:21px'>
                <td class='nomor_column_11'>(1)</td>
                <td colspan=2 class='nomor_column_11'>(2)</td>
                <td class='nomor_column_11'>(3)</td>
                <td class='nomor_column_11'>(4)</td>
                <td class='nomor_column_11'>(5)</td>
                <td class='nomor_column_11'>(6)</td>
                <td class='nomor_column_11'>(7)</td>
                <td class='nomor_column_11'>(8)</td>
                <td class='nomor_column_11'>(9)</td>
                <td class='nomor_column_11'>(10)</td>
            </tr>
            <tr style='height:22.5pt'>
                <td colspan=3 class='header_isi_column_12'>UTAMA</td>
                <td class='header_isi_column_12'>&nbsp;</td>
                <td class='header_isi_column_12'>&nbsp;</td>
                <td class='header_isi_column_12'>&nbsp;</td>
                <td class='header_isi_column_12'>&nbsp;</td>
                <td class='header_isi_column_12'>&nbsp;</td>
                <td class='header_isi_column_12'>&nbsp;</td>
                <td class='header_isi_column_12'>&nbsp;</td>
                <td class='header_isi_column_12'>&nbsp;</td>
            </tr>
            @foreach ($ckp->ckpItem as $itemCKP)
            <tr style='height:20px'>
                <td class='isi_column_center'>{{ $loop->index + 1}}</td>
                <td class='isi_column_left' colspan="2">{{$itemCKP->nama}}</td>
                <td class='isi_column_center'>{{$itemCKP->satuan}}</td>
                <td class='isi_column_center'>{{$itemCKP->target}}</td>
                <td class='isi_column_center'>{{$itemCKP->realisasi}}</td>
                <td class='isi_column_center'>{{$itemCKP->capaian_tulis}}</td>
                <td class='isi_column_center'>&nbsp;</td>
                <td class='isi_column_center'>&nbsp;</td>
                <td class='isi_column_center'>&nbsp;</td>
                <td class='isi_column_center'>&nbsp;</td>
            </tr>
            @endforeach
            <tr class="kosong" style='height:22.5pt'>
                <td colspan=3 class='header_isi_column_12'>TAMBAHAN</td>
                <td class='header_isi_column_12'>&nbsp;</td>
                <td class='header_isi_column_12'>&nbsp;</td>
                <td class='header_isi_column_12'>&nbsp;</td>
                <td class='header_isi_column_12'>&nbsp;</td>
                <td class='header_isi_column_12'>&nbsp;</td>
                <td class='header_isi_column_12'>&nbsp;</td>
                <td class='header_isi_column_12'>&nbsp;</td>
                <td class='header_isi_column_12'>&nbsp;</td>
            </tr>
            <tr style='height:20px'>
                <td class='isi_column_center'>&nbsp;</td>
                <td colspan=2 class='isi_column_center'>&nbsp;</td>
                <td class='isi_column_center'>&nbsp;</td>
                <td class='isi_column_center'>&nbsp;</td>
                <td class='isi_column_center'>&nbsp;</td>
                <td class='isi_column_center'>&nbsp;</td>
                <td class='isi_column_center'>&nbsp;</td>
                <td class='isi_column_center'>&nbsp;</td>
                <td class='isi_column_center'>&nbsp;</td>
                <td class='isi_column_center'>&nbsp;</td>
            </tr>
            <tr style='height:22.5pt'>
                <td colspan=9 class='header_isi_column_12' style="text-align:center;vertical-align: middle;">JUMLAH</td>
                <td class="header_isi_column_12">&nbsp;</td>
                <td class="header_isi_column_12" style='border-left:none; background: gray;'>&nbsp;</td>
            </tr>
            <tr style='height:22.5pt'>
                <td colspan=6 class='header_isi_column_12' style="text-align:center;vertical-align: middle;">RATA-RATA</td>
                <td class='header_isi_column_12' style="text-align:center;vertical-align: middle;">{{$capaian}}</td>
                <td class="header_isi_column_12">&nbsp;</td>
                <td class="header_isi_column_12">&nbsp;</td>
                <td rowspan=2 class="header_isi_column_12" style='background: gray;'>&nbsp;</td>
                <td rowspan=2 class="header_isi_column_12" style='background: gray;'>&nbsp;</td>
            </tr>
            <tr style='height:22.5pt'>
                <td colspan=6 class='header_isi_column_12' style="text-align:center;vertical-align: middle;">CAPAIAN KINERJA PEGAWAI (CKP)</td>
                <td colspan=2 class='header_isi_column_12' style="text-align:center;vertical-align: middle;">{{$capaian}}</td>
                <td class=header_isi_column_12>&nbsp;</td>
            </tr>
            <tr style='height:12.75pt'>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong"></td>
            </tr>
            <tr style='height:15pt'>
                <td class="kosong"></td>
                <td class="kosong" colspan=2 style="white-space: nowrap; font-weight:700;">Penilaian Kinerja</td>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong"></td>
            </tr>
            <tr style='height:15pt'>
                <td class="kosong"></td>
                <td class="kosong" colspan=2 style="white-space: nowrap;">Tanggal : {{$ckp->ckp_r_ttd}}</td>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong"></td>
            </tr>
            <tr style='height:9pt'>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong"></td>
            </tr>
            <tr style='height:15pt'>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong" style="text-align:center;white-space: nowrap;">Pegawai Yang Dinilai</td>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong" style="text-align:center;white-space: nowrap;">Pejabat Penilai</td>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong"></td>
            </tr>
            <tr height=50 style='height:35pt'>
                <td height=50 class='kosong' style='height:35pt'>&nbsp;</td>
                <td class="kosong">&nbsp;</td>
                <td class="kosong">&nbsp;</td>
                <td class="kosong">&nbsp;</td>
                <td class="kosong">&nbsp;</td>
                <td class="kosong">&nbsp;</td>
                <td class="kosong">&nbsp;</td>
                <td class="kosong">&nbsp;</td>
                <td class="kosong">&nbsp;</td>
                <td class="kosong">&nbsp;</td>
                <td class="kosong">&nbsp;</td>
            </tr>
            <tr style='height:15pt'>
                <td class="kosong" ></td>
                <td class="kosong"></td>
                <td class="kosong" style="text-align:center;white-space: nowrap;font-weight:700;">{{ auth()->user()->nama }}</td>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong" colspan=3 style="text-align:center;white-space: nowrap;font-weight:700;">{{$ckp->ttd_r->nama}}</td>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong"></td>
            </tr>
            <tr style='height:15pt'>
                <td class="kosong" ></td>
                <td class="kosong"></td>
                <td class="kosong" style="text-align:center;white-space: nowrap;font-weight:700;">NIP. {{auth()->user()->nip_baru}}</td>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong" colspan=3 style="text-align:center;white-space: nowrap;font-weight:700;">NIP. {{$ckp->ttd_r->nip_baru}}</td>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong"></td>
            </tr>
            <tr style='height:2.25pt'>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong"></td>
                <td class="kosong"></td>
            </tr>
        </table>

    </div>


    <!----------------------------->
    <!--END OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD-->
    <!----------------------------->
</body>

</html>
